version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  mysql-data: