version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html/
    stdin_open: true
    tty: true

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./db/init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  mysql-data: