version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ooplogin
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./db/init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  mysql-data: