version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
      - composer_installation
    ports:
      - "2003:80"
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html/
      - ./vendor:/var/www/vendor
    stdin_open: true
    tty: true
    networks:
      frontend:
        aliases:
          - projets-tomcat.isep.fr:172.27.32.14:8080
      backend:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./db/init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      backend:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      backend:

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs
    networks:
      backend:

volumes:
  mysql-data:

networks:
  frontend:
  backend: